# Generated by Django 5.0.6 on 2024-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_power_color_alter_power_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='spren',
            name='powers',
            field=models.ManyToManyField(to='main_app.power'),
        ),
    ]
